spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: true
    gateway:
      routes:
        - id: product_route
          uri: lb://zmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://zmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://zmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/admin/$\{segment}

  application:
    name: zmall-gateway
server:
  port: 88